logging:
  level: INFO
  
  appenders:
    - type: console
      threshold: ALL
      timeZone: system     
#timeZone: EAT
#  loggers:
#    com.dave.apis: DEBUG

server:
  type: simple
  applicationContextPath: /batigen
  adminContextPath: /batigen/admin
  connector: 
    port: 12345
    type: http
    
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/batian_db?autoReconnect=true&useSSL=false
  user: root
  password: root 
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 2s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
  
swagger:
  resourcePackage: com.dave.apis.batigen.resources
